### PR TITLE
Simplifications

### PR DESCRIPTION
**Pull request by Turbo87**
I did those changes under the assumption that everything would be passed through `ember-cli-babel` anyway. If that assumption is incorrect feel free to close the PR :)

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you test out in an app?  I just realized we have no tests in this repo 😭

**Comment by Turbo87** [comment]
seems to work fine when tested via `npm link`

**Comment by rwjblue** [comment]
published as 2.1.0

**Comment by Turbo87** [comment]
muchas gracias

**Pull request merged**
